version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    mem_limit: 4g
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - /opt/elasticsearch/:/usr/share/elasticsearch/data/
      # - /etc/localtime:/etc/localtime:ro
    # depends_on:
    #   - fluent-bit
    # logging:
    #   driver: fluentd
      # options:
      #   tag: efk.elasticsearch
    # networks:
    #   - test

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    mem_limit: 2g
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    ports:
      - 5601:5601
    # depends_on:
    #   - fluent-bit
    #   - elasticsearch
    # logging:
    #   driver: fluentd
      # options:
      #   tag: efk.kibana

  fluent-bit:
    image: fluent/fluent-bit:2.2.2
    container_name: fluent-bit
    restart: always
    command:
      - /fluent-bit/bin/fluent-bit
      - --config=/fluent-bit/etc/fluent-bit.conf
    environment:
      - FLB_ES_HOST=elasticsearch
      - FLB_ES_HOST=9200
    ports:
      - 24224:24224
      - "24224:24224/udp"
    volumes:
      - ./config/:/fluent-bit/etc/:ro
      - /etc/localtime:/etc/localtime:ro
  #   logging:
  #     driver: fluentd
  #     options:
  #       tag: efk.fluentbit
  #       # fluentd-address: 192.168.0.160:24224
  #   # networks:
  #   #   - test