version: "3.8"

services:
  kafka01:
    container_name: kafka01
    image: kafka:3.6.1
    build: 
      context: docker-build
    ports:
        - 15311:15311
    restart: always
    volumes:
      - ./config/kafka01/server.properties:/kafka/config/kraft/server.properties
      - data_kafka01:/kafka/logs

  kafka02:
    container_name: kafka02
    image: kafka:3.6.1
    build: 
      context: docker-build
    ports:
        - 15312:15312
    restart: always
    volumes:
      - ./config/kafka02/server.properties:/kafka/config/kraft/server.properties
      - data_kafka02:/kafka/logs

  kafka03:
    container_name: kafka03
    image: kafka:3.6.1
    build: 
      context: docker-build
    ports:
        - 15313:15313
    restart: always
    volumes:
      - ./config/kafka03/server.properties:/kafka/config/kraft/server.properties
      - data_kafka03:/kafka/logs

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "6080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=develop
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka01:9092,kafka02:9092,kafka03:9092

volumes:
  data_kafka01:
  data_kafka02:
  data_kafka03: